"""
Quick A/B score tracking helper for Crunch Synth projects.

Daily workflow
1) Copy current metrics from each project page on hub.crunchdao.com
    - score_recent
    - score_steady
    - score_anchor
2) Append one snapshot per project.
3) Run summary to compare latest values.

Copy/paste commands (run from workspace root)

Add invisible-fox snapshot:
python track_ab_scores.py add --project invisible-fox --submission-id 16 --score-recent 0.845 --score-steady 0.923 --score-anchor 0.731 --anchor-1h 0.800 --anchor-24h 0.750 --notes "daily snapshot"

Add realistic-gazelle snapshot:
python track_ab_scores.py add --project realistic-gazelle --submission-id 21 --score-recent 0.861 --score-steady 0.928 --score-anchor 0.742 --anchor-1h 0.810 --anchor-24h 0.760 --notes "daily snapshot"

View latest comparison:
python track_ab_scores.py summary

Notes
- Use UTC timestamps generated by this script for consistency.
- Keep submission_id in sync after each new push.
- Lower CRPS is better in Synth; compare recent trends over multiple days.
"""

import argparse
import csv
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Optional

ROOT = Path(__file__).resolve().parent
CSV_PATH = ROOT / "ab_score_log.csv"
PROJECTS = ["invisible-fox", "realistic-gazelle"]


def ensure_csv_exists(path: Path) -> None:
    if path.exists():
        return
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(
            f,
            fieldnames=[
                "timestamp_utc",
                "date",
                "project",
                "submission_id",
                "score_recent",
                "score_steady",
                "score_anchor",
                "anchor_1h",
                "anchor_24h",
                "notes",
            ],
        )
        writer.writeheader()


def parse_float_or_none(value: Optional[str]) -> Optional[float]:
    if value is None or value == "":
        return None
    return float(value)


def parse_int_or_none(value: Optional[str]) -> Optional[int]:
    if value is None or value == "":
        return None
    return int(value)


def append_entry(
    path: Path,
    *,
    project: str,
    submission_id: Optional[int],
    score_recent: Optional[float],
    score_steady: Optional[float],
    score_anchor: Optional[float],
    anchor_1h: Optional[float],
    anchor_24h: Optional[float],
    notes: str,
) -> None:
    now = datetime.now(timezone.utc)
    row = {
        "timestamp_utc": now.isoformat(),
        "date": now.date().isoformat(),
        "project": project,
        "submission_id": "" if submission_id is None else str(submission_id),
        "score_recent": "" if score_recent is None else f"{score_recent:.6f}",
        "score_steady": "" if score_steady is None else f"{score_steady:.6f}",
        "score_anchor": "" if score_anchor is None else f"{score_anchor:.6f}",
        "anchor_1h": "" if anchor_1h is None else f"{anchor_1h:.6f}",
        "anchor_24h": "" if anchor_24h is None else f"{anchor_24h:.6f}",
        "notes": notes,
    }
    with path.open("a", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=list(row.keys()))
        writer.writerow(row)


def read_rows(path: Path) -> List[Dict[str, str]]:
    if not path.exists():
        return []
    with path.open("r", newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        return list(reader)


def latest_by_project(rows: List[Dict[str, str]]) -> Dict[str, Dict[str, str]]:
    latest: Dict[str, Dict[str, str]] = {}
    for row in rows:
        project = row["project"]
        if project not in PROJECTS:
            continue
        if project not in latest or row["timestamp_utc"] > latest[project]["timestamp_utc"]:
            latest[project] = row
    return latest


def print_summary(path: Path) -> None:
    rows = read_rows(path)
    if not rows:
        print("No score entries yet. Add entries with the 'add' command.")
        return

    latest = latest_by_project(rows)
    print("Latest entries:")
    for project in PROJECTS:
        row = latest.get(project)
        if not row:
            print(f"- {project}: no entries")
            continue
        print(
            f"- {project}: submission={row['submission_id'] or '-'} "
            f"recent={row['score_recent'] or '-'} "
            f"steady={row['score_steady'] or '-'} "
            f"anchor={row['score_anchor'] or '-'} "
            f"a1h={row.get('anchor_1h') or '-'} "
            f"a24h={row.get('anchor_24h') or '-'} "
            f"date={row['date']}"
        )

    left = latest.get(PROJECTS[0])
    right = latest.get(PROJECTS[1])
    if left and right:
        left_recent = parse_float_or_none(left.get("score_recent"))
        right_recent = parse_float_or_none(right.get("score_recent"))
        if left_recent is not None and right_recent is not None:
            delta = left_recent - right_recent
            winner = PROJECTS[0] if delta > 0 else PROJECTS[1] if delta < 0 else "tie"
            print(f"Recent-score delta ({PROJECTS[0]} - {PROJECTS[1]}): {delta:+.6f} | winner: {winner}")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Track A/B Crunch score snapshots for two projects.")
    subparsers = parser.add_subparsers(dest="command", required=True)

    add = subparsers.add_parser("add", help="Add one score snapshot entry.")
    add.add_argument("--project", choices=PROJECTS, required=True)
    add.add_argument("--submission-id", type=int)
    add.add_argument("--score-recent", type=float)
    add.add_argument("--score-steady", type=float)
    add.add_argument("--score-anchor", type=float)
    add.add_argument("--anchor-1h", type=float)
    add.add_argument("--anchor-24h", type=float)
    add.add_argument("--notes", default="")

    subparsers.add_parser("summary", help="Show latest score snapshot per project.")

    return parser


def main() -> None:
    parser = build_parser()
    args = parser.parse_args()

    ensure_csv_exists(CSV_PATH)

    if args.command == "add":
        append_entry(
            CSV_PATH,
            project=args.project,
            submission_id=parse_int_or_none(args.submission_id),
            score_recent=parse_float_or_none(args.score_recent),
            score_steady=parse_float_or_none(args.score_steady),
            score_anchor=parse_float_or_none(args.score_anchor),
            anchor_1h=parse_float_or_none(args.anchor_1h),
            anchor_24h=parse_float_or_none(args.anchor_24h),
            notes=args.notes,
        )
        print(f"Added snapshot for {args.project} in {CSV_PATH}")
    elif args.command == "summary":
        print_summary(CSV_PATH)


if __name__ == "__main__":
    main()
